[package]
name = "sensevoice-sys"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "FFI bindings for SenseVoice.cpp"

[lib]
name = "sensevoice_sys"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }

[build-dependencies]
bindgen = "0.69"
cc = "1.0"
